{% set name = "persim" %}
{% set version = "0.3.4" %}
{% set sha256 = "2c2a43d44f8373ebc13c2dd9ef7f45d817d5dc8283e3b9a418b432315cb17593" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scikit-learn
    - numpy
    - matplotlib-base
    - scipy
    - hopcroftkarp
    - deprecated
    - joblib

test:
  imports:
    - persim

about:
  home: http://github.com/scikit-tda/persim
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Distances and representations of persistence diagrams

  description: |
    Persim is a Python package for many tools used in analyzing Persistence Diagrams. It currently houses implementations of Persistence Images, Bottleneck distance, Sliced Wasserstein Kernel, Heat Kernel, and Diagram plotting
  doc_url: http://persim.scikit-tda.org/
  dev_url: https://github.com/scikit-tda/persim

extra:
  recipe-maintainers:
    - sauln
    - bdice
