{% set name = "persim" %}
{% set version = "0.3.0" %}
{% set sha256 = "5db2f7f65b1ad7b2cbfa254afb692ca0a91aeb686e82d6905838c41f516e6a13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - scikit-learn
    - numpy
    - matplotlib-base
    - scipy
    - hopcroftkarp

test:
  imports:
    - persim

about:
  home: http://github.com/scikit-tda/persim
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Distances and representations of persistence diagrams

  description: |
    Persim is a Python package for many tools used in analyzing Persistence Diagrams. It currently houses implementations of Persistence Images, Bottleneck distance, Sliced Wasserstein Kernel, Heat Kernel, and Diagram plotting
  doc_url: http://persim.scikit-tda.org/
  dev_url: https://github.com/scikit-tda/persim

extra:
  recipe-maintainers:
    - sauln
    - bdice
