{% set name = "persim" %}
{% set version = "0.1.1" %}
{% set sha256 = "932bb0489d4dc158e4f007ec609c61e4700003d882d8e7bdac218b70d14ce9cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - scikit-learn
    - numpy
    - matplotlib
    - scipy
    - hopcroftkarp

test:
  imports:
    - persim

about:
  home: http://github.com/scikit-tda/persim
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Distances and representations of persistence diagrams'

  description: |
    Persim is a Python package for many tools used in analyzing Persistence Diagrams. It currently houses implementations of Persistence Images, Bottleneck distance, Sliced Wasserstein Kernel, Heat Kernel, and Diagram plotting
  doc_url: http://persim.scikit-tda.org/
  dev_url: https://github.com/scikit-tda/persim

extra:
  recipe-maintainers:
    - sauln
    - bdice
