{% set name = "persim" %}
{% set version = "0.3.5" %}
{% set sha256 = "ab2972de4231f4743bcc34f449f525b2a646aa26dd5ec7d6d5d2fd1cda506498" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scikit-learn
    - numpy
    - matplotlib-base
    - scipy
    - hopcroftkarp
    - deprecated
    - joblib

test:
  imports:
    - persim

about:
  home: http://github.com/scikit-tda/persim
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Distances and representations of persistence diagrams

  description: |
    Persim is a Python package for many tools used in analyzing Persistence Diagrams. It currently houses implementations of Persistence Images, Bottleneck distance, Sliced Wasserstein Kernel, Heat Kernel, and Diagram plotting
  doc_url: http://persim.scikit-tda.org/
  dev_url: https://github.com/scikit-tda/persim

extra:
  recipe-maintainers:
    - sauln
    - bdice
